### PR TITLE
Fix environment variable persistence

### LINKED ISSUE #60: Environment variables are persisted in Ruby 3.0
### Describe the problem

The environment variables options (in its two forms) behave differently, where one form seems to persist the variables even for subsequent commands.

### Steps to reproduce the problem

```ruby
require 'tty/command'

shell = TTY::Command.new

env1 = { a: "a", b: "b" }
env2 = { c: "d", d: "d" }

# PASS
shell.run :echo, env: env1
# => Running ( export A="a" B="b" ; echo )

# FAIL - env is expected not to be used here
shell.run :echo
# => Running ( export A="a" B="b" ; echo )

# FAIL - env1 was merged with env2 here, unexpectedly
shell.run env2, :echo
# => Running ( export C="d" D="d" A="a" B="b" ; echo )

# 1 x PASS: env2 was NOT persisted from the previous call
# 1 x FAIL: env1 is still here
shell.run :echo
# => Running ( export A="a" B="b" ; echo )
```

### Actual behaviour

Environment variables were sometimes persisted and used in subsequent commands, even if they did not have `env` setting.

### Expected behaviour

Expected env vars to only influence the running command, and not contaminate subsequent commands.

Side note: In case there is a desire to set a global environment, I expected it to be defined in the form of `TTY::Command.new env: { ... }`

### Additional notes

I was also wondering why the environment is prepended to the command in this form:

```shell
export VAR="val" VAR2="val" ; command
```

instead of this form (no `export`, no semicolon):

```shell
VAR="val" VAR2="val" command
```

which, to my understanding, it the common way of setting environment variables for a single command.

### Describe your environment

* OS version: Ubuntu 18
* Ruby version: ruby 3.0.0p0
* TTY::Command version: 0.10.0

### PR DESCRIPTION
**Pull request by DannyBen**
Closes #60 

I added test in the most appropriate place I could think of and verified the test fails without the fix.
All other specs pass locally.

### CODE REVIEW

File: spec/unit/run_spec.rb [hunk 1]
```diff
@@ -160,4 +160,15 @@
       "[\e[32m#{uuid}\e[0m] Finished in x seconds with exit status 0 (\e[32;1msuccessful\e[0m)\n"
     ])
   end
+
+  it "does not persist environment variables" do
+    output = StringIO.new
+    command = TTY::Command.new(output: output)
+
+    out, _err = command.run("env | grep FOO", env: {foo: 1})
```
[the remark this answers is not in the document]
Comment (DannyBen) [reply spec/unit/run_spec.rb:168]: In regards to these style issues - I agree, but followed the style already present in the code and specs

File: lib/tty/command/cmd.rb [hunk 2]
```diff
@@ -64,7 +64,7 @@ def initialize(env_or_cmd, *args)
       #
       # @api public
       def update(options)
-        @options.update(options.update(@options))
+        @options.update(options.merge(@options))
```
Comment (piotrmurach) [inline lib/tty/command/cmd.rb:67]: Great catch! Let's raise a glass to state mutation.

File: spec/unit/run_spec.rb [hunk 3]
```diff
@@ -160,4 +160,15 @@
...
+    expect(out.chomp).to eq("FOO=1")
+    out, _err = command.run!("env | grep FOO")
+    expect(out).to eq("")
+  end
```
Comment (piotrmurach) [inline spec/unit/run_spec.rb:172]: I'd consider examining the `output` format as it will show the commands that are run with the `export` statement. Also, it would be good to get this running on Windows which probably won't have `grep` utility. I tend to stay with the safer `echo` command.

**Review by piotrmurach — COMMENTED** [review]
Thank you for contributing this patch so fast! Before I merge, could you please see if you can resolve my comment about the test? Don't worry about the style issue I will look into making them consistent.

File: spec/unit/run_spec.rb (hunk 3 above)
Comment (DannyBen) [reply spec/unit/run_spec.rb:172]: Sure, updating.

Comment (DannyBen) [reply spec/unit/run_spec.rb]: I updated the tests, borrowing from a similar test in the same spec.

If it was my code, I would have probably opted to use something like:

```ruby
expect(output.string).to include "..."
```
instead of all the `readlines` acrobatics, but since your gems need to work on more environments, I figured I play it safe since you must have a reason for doing it this way.

---

As a side note, the styling bot is super annoying - if it was a real robot, I would have disassembled it and sold it for parts... 😏

**Review by piotrmurach — COMMENTED** [review]
Sorry to be a pain and promise this to be the last thing before a merge. Would you have time to add a changelog entry(no need for the release version, only fix entry) and if possible update code style issues? I went through specs and updated them today to reflect the rubocop settings so if you could pull in the changes and rebase that would be great. Thank you.

File: spec/unit/run_spec.rb (hunk 3 above)
Comment (piotrmurach) [reply spec/unit/run_spec.rb]: I'm ok with any approach that verifies behaviour and passes tests. I updated all the test setup to work on GitHub Actions and Appveyor so you should get immediate feedback. The style bot is annoying but it has good intentions...😉

**Comment by DannyBen** [comment]
> Would you have time to...

Yes. Stand by :)

**Comment by DannyBen** [comment]
- Pulled and merged upstream master
- Added changelog entry
- Resolved all but one Hound complaints
- Simplified the spec to compare only to the part of the string we care about
