### PR TITLE
[WIP] Add PrettyOnError printer

### LINKED ISSUE #41: Print output only on error
Is it possible to only print the command output only if it failed?

So it would print:

```
[hash] Running command
```

when it succeeds, and:

```
[hash] Running command
[hash] ** BUILD FAILED **
[hash] Finished in 2.788 seconds with exit status 65 (failed)
```

when it fails.

### PR DESCRIPTION
**Pull request by revolter**
- [x] Add documentation in the `README`
- [x] Add unit tests

Closes #41.

### CODE REVIEW

File: lib/tty/command.rb [hunk 1]
```diff
@@ -203,7 +204,7 @@ def use_printer(class_or_name, options)
     #
     # @api private
     def find_printer_class(name)
-      const_name = name.to_s.capitalize.to_sym
+      const_name = name.to_s.split('_').map(&:capitalize).join('').to_sym
```
Comment (revolter) [inline lib/tty/command.rb]: For one word printers, the split will simply return an array with one element (the initial string), so it works the same.

File: lib/tty/command/printers/pretty.rb [hunk 2]
```diff
@@ -38,14 +38,20 @@ def print_command_exit(cmd, status, runtime, *args)
         # Write message out to output
         #
         # @api private
-        def write(message, uuid = nil)
+        def write(message, uuid = nil, dry_run = false)
```
Comment (revolter) [inline lib/tty/command/printers/pretty.rb]: I guess it's not a problem to have this here, as it defaults to `false` not to break the `Pretty` printer. Also, I decided to modify this because the new one is based on this so I wanted to avoid duplicating code.

File: lib/tty/command/printers/pretty.rb [hunk 3]
```diff
@@ -38,14 +38,20 @@ def print_command_exit(cmd, status, runtime, *args)
...
           uuid_needed = options.fetch(:uuid) { true }
           out = []
           if uuid_needed
             out << "[#{decorate(uuid, :green)}] " unless uuid.nil?
           end
           out << "#{message}\n"
-          output << out.join
+          result = out.join
```
Comment (revolter) [inline lib/tty/command/printers/pretty.rb]: Added this to avoid calling `join` in two different places

File: lib/tty/command/printers/pretty_on_error.rb [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+          super(cmd, *args)
+
+          @out_data = ''
+          @err_data = ''
+        end
+
+        def print_command_out_data(cmd, *args)
+          message = args.map(&:chomp).join(' ')
+
+          @out_data += write("\t#{message}", cmd.uuid, true)
```
Comment (revolter) [inline lib/tty/command/printers/pretty_on_error.rb]: Don't know if I can replace these with a `super` call, so the line `20` is actually duplicated.

File: lib/tty/command/printers/pretty_on_error.rb [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+          message = args.map(&:chomp).join(' ')
+
+          @err_data += write("\t" + decorate(message, :red), cmd.uuid, true)
+        end
+
+        def print_command_exit(cmd, status, runtime, *args)
+          unless status == 0
+            output << @out_data
+            output << @err_data
+          end
```
Comment (revolter) [inline lib/tty/command/printers/pretty_on_error.rb]: Make sure the output and error are printed before the exit log, as it does by using the `Pretty` printer directly.

File: lib/tty/command/printers/pretty_on_error.rb [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+
+          super(cmd, status, runtime, *args)
+        end
+      end # PrettyOnError
+    end # Printers
+  end # Command
+end # TTY
```
[the remark this answers is not in the document]
Comment (revolter) [reply lib/tty/command/printers/pretty_on_error.rb]: Are you sure?

**Comment by revolter** [comment]
Could we add an option to the `Pretty` printer instead? Like `TTY::Command.new(printer: :pretty, printer_options: [ only_on_error: true ])`?

**Comment by piotrmurach** [comment]
I know it feels weird duplicating code, but I do like the simplicity of having a new printer type. Similarly, I do like simplicity of choosing a printer. The configuration seems cumbersome and complicates api for me, wouldn't you agree? Ultimately, this is a taste decision really, there is no right way.

File: lib/tty/command.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (revolter) [reply lib/tty/command.rb]: Are you sure? Because you also use `'` for simple strings, and `"` when interpolation is needed.

File: lib/tty/command/printers/pretty.rb [hunk 7]
```diff
@@ -38,14 +38,20 @@ def print_command_exit(cmd, status, runtime, *args)
...
+
+          if dry_run
```
[the remark this answers is not in the document]
Comment (revolter) [reply lib/tty/command/printers/pretty.rb]: Are you referring to the `dry_runner` command? Meaning that maybe this new parameter I added should be renamed to something like `return_command_instead_of_displaying`.

**Comment by revolter** [comment]
What if I completely rever the `Pretty` printer, and duplicate the `write` method implementation in the `PrettyOnError` printer, while still extending the `Pretty` printer, as I kind of like the implementation simplicity (and possible future maintenance).

**Comment by revolter** [comment]
@piotrmurach, So?

**Comment by piotrmurach** [comment]
@revolter Sound good to me. You can close this PR and open a new one with your new suggestion, or carry on with this one and then once ready squish all the changes into one commit. Whatever makes it easier for you. I will review asap.

**Comment by revolter** [comment]
There is no need for a squash. You can do so when merging:

[screenshot](https://blog.github.com/2016-04-01-squash-your-commits)

**Comment by revolter** [comment]
I just noticed that the printers already receive an options hash. How does this sound:

```ruby
cmd = TTY::Command.new

cmd.run('build', output_on_error: true)
cmd.run('notify')
```

?

This way, there are 3 advantages:

- There won't be a need for a (quite specific) new printer
- It would work with any printer (maybe even a custom one)
- You could be able to run some commands that print the output only on error, and other commands that print the output when it happens

**Comment by piotrmurach** [comment]
I like your suggestion, though I haven't had time to think it through in depth. The only further suggestion to make would be to name it `print/output_only_on_error`, otherwise user may wonder if this means that normally errors are not printed, also it specifies that no other output but error is printed thus removing any ambiguity.

**Comment by revolter** [comment]
I will implement that idea in this PR and let you know when it's finished to take a look.

**Comment by revolter** [comment]
@piotrmurach, Finally, I finished it 😅

**Comment by piotrmurach** [comment]
Thanks! ♥️

**Comment by revolter** [comment]
Thank you for merging! ♥️ Can you also release a new version? 😃

**Comment by piotrmurach** [comment]
I will once I fix the https://github.com/piotrmurach/tty-command/issues/43 which I believe to be  important and also fairly tricky.

**Comment by piotrmurach** [comment]
Released `v0.8.0` with your addition as well as a new output reading implementation that handles timeouts.
